### PR TITLE
Update node.js in circleci, simplyify npm scripts

### PR DESCRIPTION
**Pull request by umaar**

### CODE REVIEW

**Comment by solidgoldpig** [comment]
Why stop using npm-run-all? And changing the npm test structure from other repos?

**Comment by umaar** [comment]
@solidgoldpig 

Was having a think about this one and here are my thoughts:

pros: I think the way we're using it, it is not serving any benefits at all

cons:

- extra dependency (which itself includes of a bunch of others)
- it encourages loads of extra layers of indirection, e.g. 'this script calls that, then that calls this' - but I don't see the benefit

The diff should clearly demonstrate the (lack of) necessity of `npm-run-all`? We do not have enough scripts that makes this useful

On the note of "it's how other projects do it", I thought we'd start in some places and expand this elsewhere...but maybe you can make your case for why you think it's useful - specifically focussing on the before/after of this package.json?

**Comment by umaar** [comment]
Parallelization! Totally did not think about that, will undo that part

**Comment by umaar** [comment]
@solidgoldpig reverted, ready for review

**Review by solidgoldpig — APPROVED** [review]

**Pull request merged**
